# auto-mpg 데이터 전처리 연습

In [27]:
import urllib.request as req
import pandas as pd
import numpy as np

## [1] 데이터 파일로 저장

In [28]:
# urlretrieve 사용해서 파일로 저장하기
req.urlretrieve("https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data", 'mpg.csv')
req.urlretrieve("https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.names", 'mpg-col.csv')

('mpg-col.csv', <http.client.HTTPMessage at 0x7fa3e0920f90>)

In [29]:
# 파일 불러오기
data = pd.read_csv("mpg.csv", header=None, sep="\s+")
columns = pd.read_csv("mpg-col.csv", header=None, sep="\n", skiprows=32, nrows=9)

In [30]:
# 컬럼명 확인
columns

                                                   0
0                       1. mpg:           continuous
1            2. cylinders:     multi-valued discrete
2                       3. displacement:  continuous
3                       4. horsepower:    continuous
4                       5. weight:        continuous
5                       6. acceleration:  continuous
6            7. model year:    multi-valued discrete
7            8. origin:        multi-valued discrete
8      9. car name:      string (unique for each ...

In [31]:
# 데이터프레임에 컬럼명 지정해줌
data.columns = ["mpg", "cylinders", "displacement", "horsepower", "weight", "acceleration", "model-year", "origin", "car-name"]

In [32]:
# 확인
data

,mpg,cylinders,displacement,horsepower,weight,acceleration,model-year,origin,car-name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw pickup
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford ranger
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy s-10

## [2] 데이터 전처리

In [33]:
# 데이터 타입 확인
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    float64
 5   acceleration  398 non-null    float64
 6   model-year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car-name      398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [34]:
# 데이터 특성 확인
for i in data.columns:
    print(f"{i} 컬럼의 특성 : ", data[i].unique(), sep="\n")

mpg 컬럼의 특성 :
[18.  15.  16.  17.  14.  24.  22.  21.  27.  26.  25.  10.  11.   9.
 28.  19.  12.  13.  23.  30.  31.  35.  20.  29.  32.  33.  17.5 15.5
 14.5 22.5 24.5 18.5 29.5 26.5 16.5 31.5 36.  25.5 33.5 20.5 30.5 21.5
 43.1 36.1 32.8 39.4 19.9 19.4 20.2 19.2 25.1 20.6 20.8 18.6 18.1 17.7
 27.5 27.2 30.9 21.1 23.2 23.8 23.9 20.3 21.6 16.2 19.8 22.3 17.6 18.2
 16.9 31.9 34.1 35.7 27.4 25.4 34.2 34.5 31.8 37.3 28.4 28.8 26.8 41.5
 38.1 32.1 37.2 26.4 24.3 19.1 34.3 29.8 31.3 37.  32.2 46.6 27.9 40.8
 44.3 43.4 36.4 44.6 40.9 33.8 32.7 23.7 23.6 32.4 26.6 25.8 23.5 39.1
 39.  35.1 32.3 37.7 34.7 34.4 29.9 33.7 32.9 31.6 28.1 30.7 24.2 22.4
 34.  38.  44. ]
cylinders 컬럼의 특성 :
[8 4 6 3 5]
displacement 컬럼의 특성 :
[307.  350.  318.  304.  302.  429.  454.  440.  455.  390.  383.  340.
 400.  113.  198.  199.  200.   97.  110.  107.  104.  121.  360.  140.
  98.  232.  225.  250.  351.  258.  122.  116.   79.   88.   71.   72.
  91.   97.5  70.  120.   96.  108.  155.   68.  114.  156.   76.   83.
  90.  231.  262.  134.  119.  171.  115.  101.  305.   85.  130.  168.
 111.  260.  151.  146.   80.   78.  105.  131.  163.   89.  267.   86.
 183.  141.  173.  135.   81.  100.  145.  112.  181.  144. ]
horsepower 컬럼의 특성 :
['130.0' '165.0' '150.0' '140.0' '198.0' '220.0' '215.0' '225.0' '190.0'
 '170.0' '160.0' '95.00' '97.00' '85.00' '88.00' '46.00' '87.00' '90.00'
 '113.0' '200.0' '210.0' '193.0' '?' '100.0' '105.0' '175.0' '153.0'
 '180.0' '110.0' '72.00' '86.00' '70.00' '76.00' '65.00' '69.00' '60.00'
 '80.00' '54.00' '208.0' '155.0' '112.0' '92.00' '145.0' '137.0' '158.0'
 '167.0' '94.00' '107.0' '230.0' '49.00' '75.00' '91.00' '122.0' '67.00'
 '83.00' '78.00' '52.00' '61.00' '93.00' '148.0' '129.0' '96.00' '71.00'
 '98.00' '115.0' '53.00' '81.00' '79.00' '120.0' '152.0' '102.0' '108.0'
 '68.00' '58.00' '149.0' '89.00' '63.00' '48.00' '66.00' '139.0' '103.0'
 '125.0' '133.0' '138.0' '135.0' '142.0' '77.00' '62.00' '132.0' '84.00'
 '64.00' '74.00' '116.0' '82.00']
weight 컬럼의 특성 :
[3504. 3693. 3436. 3433. 3449. 4341. 4354. 4312. 4425. 3850. 3563. 3609.
 3761. 3086. 2372. 2833. 2774. 2587. 2130. 1835. 2672. 2430. 2375. 2234.
 2648. 4615. 4376. 4382. 4732. 2264. 2228. 2046. 2634. 3439. 3329. 3302.
 3288. 4209. 4464. 4154. 4096. 4955. 4746. 5140. 2962. 2408. 3282. 3139.
 2220. 2123. 2074. 2065. 1773. 1613. 1834. 1955. 2278. 2126. 2254. 2226.
 4274. 4385. 4135. 4129. 3672. 4633. 4502. 4456. 4422. 2330. 3892. 4098.
 4294. 4077. 2933. 2511. 2979. 2189. 2395. 2288. 2506. 2164. 2100. 4100.
 3988. 4042. 3777. 4952. 4363. 4237. 4735. 4951. 3821. 3121. 3278. 2945.
 3021. 2904. 1950. 4997. 4906. 4654. 4499. 2789. 2279. 2401. 2379. 2124.
 2310. 2472. 2265. 4082. 4278. 1867. 2158. 2582. 2868. 3399. 2660. 2807.
 3664. 3102. 2875. 2901. 3336. 2451. 1836. 2542. 3781. 3632. 3613. 4141.
 4699. 4457. 4638. 4257. 2219. 1963. 2300. 1649. 2003. 2125. 2108. 2246.
 2489. 2391. 2000. 3264. 3459. 3432. 3158. 4668. 4440. 4498. 4657. 3907.
 3897. 3730. 3785. 3039. 3221. 3169. 2171. 2639. 2914. 2592. 2702. 2223.
 2545. 2984. 1937. 3211. 2694. 2957. 2671. 1795. 2464. 2572. 2255. 2202.
 4215. 4190. 3962. 3233. 3353. 3012. 3085. 2035. 3651. 3574. 3645. 3193.
 1825. 1990. 2155. 2565. 3150. 3940. 3270. 2930. 3820. 4380. 4055. 3870.
 3755. 2045. 1945. 3880. 4060. 4140. 4295. 3520. 3425. 3630. 3525. 4220.
 4165. 4325. 4335. 1940. 2740. 2755. 2051. 2075. 1985. 2190. 2815. 2600.
 2720. 1800. 2070. 3365. 3735. 3570. 3535. 3155. 2965. 3430. 3210. 3380.
 3070. 3620. 3410. 3445. 3205. 4080. 2560. 2230. 2515. 2745. 2855. 2405.
 2830. 3140. 2795. 2135. 3245. 2990. 2890. 3265. 3360. 3840. 3725. 3955.
 3830. 4360. 4054. 3605. 1925. 1975. 1915. 2670. 3530. 3900. 3190. 3420.
 2200. 2150. 2020. 2595. 2700. 2556. 2144. 1968. 2120. 2019. 2678. 2870.
 3003. 3381. 2188. 2711. 2434. 2110. 2800. 2085. 2335. 2950. 3250. 1850.
 2145. 1845. 2910. 2420. 2500. 2905. 2290. 2490. 2635. 2620. 2725. 2385.
 1755. 1875. 1760. 2050. 2215. 2380. 2320. 2210. 2350. 2615. 3230. 3160.
 2900. 3415. 3060. 3465. 2605. 2640. 2575. 2525. 2735. 2865. 3035. 1980.
 2025. 1970. 2160. 2205. 2245. 1965. 1995. 3015. 2585. 2835. 2665. 2370.
 2790. 2295. 2625.]
acceleration 컬럼의 특성 :
[12.  11.5 11.  10.5 10.   9.   8.5  8.   9.5 15.  15.5 16.  14.5 20.5
 17.5 12.5 14.  13.5 18.5 19.  13.  19.5 18.  17.  23.5 16.5 21.  16.9
 14.9 17.7 15.3 13.9 12.8 15.4 17.6 22.2 22.1 14.2 17.4 16.2 17.8 12.2
 16.4 13.6 15.7 13.2 21.9 16.7 12.1 14.8 18.6 16.8 13.7 11.1 11.4 18.2
 15.8 15.9 14.1 21.5 14.4 19.4 19.2 17.2 18.7 15.1 13.4 11.2 14.7 16.6
 17.3 15.2 14.3 20.1 24.8 11.3 12.9 18.8 18.1 17.9 21.7 23.7 19.9 21.8
 13.8 12.6 16.1 20.7 18.3 20.4 19.6 17.1 15.6 24.6 11.6]
model-year 컬럼의 특성 :
[70 71 72 73 74 75 76 77 78 79 80 81 82]
origin 컬럼의 특성 :
[1 3 2]
car-name 컬럼의 특성 :
['chevrolet chevelle malibu' 'buick skylark 320' 'plymouth satellite'
 'amc rebel sst' 'ford torino' 'ford galaxie 500' 'chevrolet impala'
 'plymouth fury iii' 'pontiac catalina' 'amc ambassador dpl'
 'dodge challenger se' "plymouth 'cuda 340" 'chevrolet monte carlo'
 'buick estate wagon (sw)' 'toyota corona mark ii' 'plymouth duster'
 'amc hornet' 'ford maverick' 'datsun pl510'
 'volkswagen 1131 deluxe sedan' 'peugeot 504' 'audi 100 ls' 'saab 99e'
 'bmw 2002' 'amc gremlin' 'ford f250' 'chevy c20' 'dodge d200' 'hi 1200d'
 'chevrolet vega 2300' 'toyota corona' 'ford pinto'
 'plymouth satellite custom' 'ford torino 500' 'amc matador'
 'pontiac catalina brougham' 'dodge monaco (sw)'
 'ford country squire (sw)' 'pontiac safari (sw)'
 'amc hornet sportabout (sw)' 'chevrolet vega (sw)' 'pontiac firebird'
 'ford mustang' 'mercury capri 2000' 'opel 1900' 'peugeot 304' 'fiat 124b'
 'toyota corolla 1200' 'datsun 1200' 'volkswagen model 111'
 'plymouth cricket' 'toyota corona hardtop' 'dodge colt hardtop'
 'volkswagen type 3' 'chevrolet vega' 'ford pinto runabout'
 'amc ambassador sst' 'mercury marquis' 'buick lesabre custom'
 'oldsmobile delta 88 royale' 'chrysler newport royal' 'mazda rx2 coupe'
 'amc matador (sw)' 'chevrolet chevelle concours (sw)'
 'ford gran torino (sw)' 'plymouth satellite custom (sw)'
 'volvo 145e (sw)' 'volkswagen 411 (sw)' 'peugeot 504 (sw)'
 'renault 12 (sw)' 'ford pinto (sw)' 'datsun 510 (sw)'
 'toyouta corona mark ii (sw)' 'dodge colt (sw)'
 'toyota corolla 1600 (sw)' 'buick century 350' 'chevrolet malibu'
 'ford gran torino' 'dodge coronet custom' 'mercury marquis brougham'
 'chevrolet caprice classic' 'ford ltd' 'plymouth fury gran sedan'
 'chrysler new yorker brougham' 'buick electra 225 custom'
 'amc ambassador brougham' 'plymouth valiant' 'chevrolet nova custom'
 'volkswagen super beetle' 'ford country' 'plymouth custom suburb'
 'oldsmobile vista cruiser' 'toyota carina' 'datsun 610' 'maxda rx3'
 'mercury capri v6' 'fiat 124 sport coupe' 'chevrolet monte carlo s'
 'pontiac grand prix' 'fiat 128' 'opel manta' 'audi 100ls' 'volvo 144ea'
 'dodge dart custom' 'saab 99le' 'toyota mark ii' 'oldsmobile omega'
 'chevrolet nova' 'datsun b210' 'chevrolet chevelle malibu classic'
 'plymouth satellite sebring' 'buick century luxus (sw)'
 'dodge coronet custom (sw)' 'audi fox' 'volkswagen dasher' 'datsun 710'
 'dodge colt' 'fiat 124 tc' 'honda civic' 'subaru' 'fiat x1.9'
 'plymouth valiant custom' 'mercury monarch' 'chevrolet bel air'
 'plymouth grand fury' 'buick century' 'chevroelt chevelle malibu'
 'plymouth fury' 'buick skyhawk' 'chevrolet monza 2+2' 'ford mustang ii'
 'toyota corolla' 'pontiac astro' 'volkswagen rabbit' 'amc pacer'
 'volvo 244dl' 'honda civic cvcc' 'fiat 131' 'capri ii' 'renault 12tl'
 'dodge coronet brougham' 'chevrolet chevette' 'chevrolet woody'
 'vw rabbit' 'dodge aspen se' 'ford granada ghia' 'pontiac ventura sj'
 'amc pacer d/l' 'datsun b-210' 'volvo 245' 'plymouth volare premier v8'
 'mercedes-benz 280s' 'cadillac seville' 'chevy c10' 'ford f108'
 'dodge d100' 'honda accord cvcc' 'buick opel isuzu deluxe'
 'renault 5 gtl' 'plymouth arrow gs' 'datsun f-10 hatchback'
 'oldsmobile cutlass supreme' 'dodge monaco brougham'
 'mercury cougar brougham' 'chevrolet concours' 'buick skylark'
 'plymouth volare custom' 'ford granada' 'pontiac grand prix lj'
 'chevrolet monte carlo landau' 'chrysler cordoba' 'ford thunderbird'
 'volkswagen rabbit custom' 'pontiac sunbird coupe'
 'toyota corolla liftback' 'ford mustang ii 2+2' 'dodge colt m/m'
 'subaru dl' 'datsun 810' 'bmw 320i' 'mazda rx-4'
 'volkswagen rabbit custom diesel' 'ford fiesta' 'mazda glc deluxe'
 'datsun b210 gx' 'oldsmobile cutlass salon brougham' 'dodge diplomat'
 'mercury monarch ghia' 'pontiac phoenix lj' 'ford fairmont (auto)'
 'ford fairmont (man)' 'plymouth volare' 'amc concord'
 'buick century special' 'mercury zephyr' 'dodge aspen' 'amc concord d/l'
 'buick regal sport coupe (turbo)' 'ford futura' 'dodge magnum xe'
 'datsun 510' 'dodge omni' 'toyota celica gt liftback' 'plymouth sapporo'
 'oldsmobile starfire sx' 'datsun 200-sx' 'audi 5000' 'volvo 264gl'
 'saab 99gle' 'peugeot 604sl' 'volkswagen scirocco' 'honda accord lx'
 'pontiac lemans v6' 'mercury zephyr 6' 'ford fairmont 4'
 'amc concord dl 6' 'dodge aspen 6' 'ford ltd landau'
 'mercury grand marquis' 'dodge st. regis' 'chevrolet malibu classic (sw)'
 'chrysler lebaron town @ country (sw)' 'vw rabbit custom'
 'maxda glc deluxe' 'dodge colt hatchback custom' 'amc spirit dl'
 'mercedes benz 300d' 'cadillac eldorado' 'plymouth horizon'
 'plymouth horizon tc3' 'datsun 210' 'fiat strada custom'
 'buick skylark limited' 'chevrolet citation' 'oldsmobile omega brougham'
 'pontiac phoenix' 'toyota corolla tercel' 'datsun 310' 'ford fairmont'
 'audi 4000' 'toyota corona liftback' 'mazda 626' 'datsun 510 hatchback'
 'mazda glc' 'vw rabbit c (diesel)' 'vw dasher (diesel)'
 'audi 5000s (diesel)' 'mercedes-benz 240d' 'honda civic 1500 gl'
 'renault lecar deluxe' 'vokswagen rabbit' 'datsun 280-zx' 'mazda rx-7 gs'
 'triumph tr7 coupe' 'ford mustang cobra' 'honda accord'
 'plymouth reliant' 'dodge aries wagon (sw)' 'toyota starlet'
 'plymouth champ' 'honda civic 1300' 'datsun 210 mpg' 'toyota tercel'
 'mazda glc 4' 'plymouth horizon 4' 'ford escort 4w' 'ford escort 2h'
 'volkswagen jetta' 'renault 18i' 'honda prelude' 'datsun 200sx'
 'peugeot 505s turbo diesel' 'volvo diesel' 'toyota cressida'
 'datsun 810 maxima' 'oldsmobile cutlass ls' 'ford granada gl'
 'chrysler lebaron salon' 'chevrolet cavalier' 'chevrolet cavalier wagon'
 'chevrolet cavalier 2-door' 'pontiac j2000 se hatchback' 'dodge aries se'
 'ford fairmont futura' 'amc concord dl' 'volkswagen rabbit l'
 'mazda glc custom l' 'mazda glc custom' 'plymouth horizon miser'
 'mercury lynx l' 'nissan stanza xe' 'honda civic (auto)' 'datsun 310 gx'
 'buick century limited' 'oldsmobile cutlass ciera (diesel)'
 'chrysler lebaron medallion' 'ford granada l' 'toyota celica gt'
 'dodge charger 2.2' 'chevrolet camaro' 'ford mustang gl' 'vw pickup'
 'dodge rampage' 'ford ranger' 'chevy s-10']

In [35]:
# 타입 맞춰주기
print("horsepower 컬럼 unique : ", data["horsepower"].unique(), sep="\n")
num = data["horsepower"] == "?"
print("? 값의 개수 : ", num.sum())

horsepower 컬럼 unique :
['130.0' '165.0' '150.0' '140.0' '198.0' '220.0' '215.0' '225.0' '190.0'
 '170.0' '160.0' '95.00' '97.00' '85.00' '88.00' '46.00' '87.00' '90.00'
 '113.0' '200.0' '210.0' '193.0' '?' '100.0' '105.0' '175.0' '153.0'
 '180.0' '110.0' '72.00' '86.00' '70.00' '76.00' '65.00' '69.00' '60.00'
 '80.00' '54.00' '208.0' '155.0' '112.0' '92.00' '145.0' '137.0' '158.0'
 '167.0' '94.00' '107.0' '230.0' '49.00' '75.00' '91.00' '122.0' '67.00'
 '83.00' '78.00' '52.00' '61.00' '93.00' '148.0' '129.0' '96.00' '71.00'
 '98.00' '115.0' '53.00' '81.00' '79.00' '120.0' '152.0' '102.0' '108.0'
 '68.00' '58.00' '149.0' '89.00' '63.00' '48.00' '66.00' '139.0' '103.0'
 '125.0' '133.0' '138.0' '135.0' '142.0' '77.00' '62.00' '132.0' '84.00'
 '64.00' '74.00' '116.0' '82.00']
? 값의 개수 :  6

In [36]:
# ? 행 날리기
index = data[data["horsepower"] == "?"].index
data = data.drop(index=index, axis=0)

In [37]:
# horsepower 컬럼 float로 변경
data["horsepower"] = pd.to_numeric(data["horsepower"])

# kml 컬럼 추가
data["kml"] = data["mpg"] * 0.425

# 필요없는 컬럼 삭제하기
data.drop(columns=["mpg", "car-name"], inplace=True)

In [38]:
# X, y 나누기
X = data.drop(columns=["kml"]).reset_index(drop=True)
y = data["kml"].reset_index(drop=True)

In [39]:
X.head(10)

,cylinders,displacement,horsepower,weight,acceleration,model-year,origin
0,8,307.0,130.0,3504.0,12.0,70,1
1,8,350.0,165.0,3693.0,11.5,70,1
2,8,318.0,150.0,3436.0,11.0,70,1
3,8,304.0,150.0,3433.0,12.0,70,1
4,8,302.0,140.0,3449.0,10.5,70,1
5,8,429.0,198.0,4341.0,10.0,70,1
6,8,454.0,220.0,4354.0,9.0,70,1
7,8,440.0,215.0,4312.0,8.5,70,1
8,8,455.0,225.0,4425.0,10.0,70,1
9,8,390.0,190.0,3850.0,8.5,70,1

In [40]:
# 범주형 데이터 추출 및 제거
X_class = X.loc[:,["cylinders", "origin"]]
X_count = X.drop(columns=["cylinders", "origin"])

X_class

     cylinders  origin
0            8       1
1            8       1
2            8       1
3            8       1
4            8       1
..         ...     ...
387          4       1
388          4       2
389          4       1
390          4       1
391          4       1

[392 rows x 2 columns]

In [41]:
X_count

     displacement  horsepower  weight  acceleration  model-year
0           307.0       130.0  3504.0          12.0          70
1           350.0       165.0  3693.0          11.5          70
2           318.0       150.0  3436.0          11.0          70
3           304.0       150.0  3433.0          12.0          70
4           302.0       140.0  3449.0          10.5          70
..            ...         ...     ...           ...         ...
387         140.0        86.0  2790.0          15.6          82
388          97.0        52.0  2130.0          24.6          82
389         135.0        84.0  2295.0          11.6          82
390         120.0        79.0  2625.0          18.6          82
391         119.0        82.0  2720.0          19.4          82

[392 rows x 5 columns]

In [42]:
# 범주형 데이터 onehot encoding 하기
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse=False)

X_cyl = pd.DataFrame(ohe.fit_transform(X_class["cylinders"].values.reshape(-1,1)))
X_ori = pd.DataFrame(ohe.fit_transform(X_class["origin"].values.reshape(-1,1)))

In [43]:
# 수치형 데이터 스케일링 하기
from sklearn.preprocessing import StandardScaler, MinMaxScaler

ss = StandardScaler()
mm = MinMaxScaler()

X_count_scal = pd.DataFrame(ss.fit_transform(X_count))

In [44]:
# 합쳐서 새로운 데이터프레임 만들기
X_new = pd.concat([X_count_scal, X_cyl, X_ori], axis=1)

In [45]:
# 컬럼네임 리셋하기
X_new = X_new.T.reset_index(drop=True).T

columns = list(X_count.columns) + ["cylinders3", "cylinders4", "cylinders5", "cylinders6", "cylinders8", "origin1", "origin2", "origin3"]

X_new.columns = columns
X_new

,displacement,horsepower,weight,acceleration,model-year,cylinders3,cylinders4,cylinders5,cylinders6,cylinders8,origin1,origin2,origin3
0,1.077290,0.664133,0.620540,-1.285258,-1.625315,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
1,1.488732,1.574594,0.843334,-1.466724,-1.625315,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
2,1.182542,1.184397,0.540382,-1.648189,-1.625315,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
3,1.048584,1.184397,0.536845,-1.285258,-1.625315,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
4,1.029447,0.924265,0.555706,-1.829655,-1.625315,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,-0.520637,-0.480448,-0.221125,0.021294,1.636410,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
388,-0.932079,-1.364896,-0.999134,3.287676,1.636410,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
389,-0.568479,-0.532474,-0.804632,-1.430430,1.636410,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
390,-0.712005,-0.662540,-0.415627,1.110088,1.636410,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
391,-0.721574,-0.584501,-0.303641,1.400433,1.636410,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

## [3] train test 나누기

In [46]:
from sklearn.model_selection import train_test_split

X_tv, X_test, y_tv, y_test = train_test_split(
    X_new, y, random_state=72, test_size=0.2
)

In [47]:
X_train, X_val, y_train, y_val = train_test_split(
    X_tv, y_tv, random_state=72, test_size=0.2
)

## [4] 모델 생성 및 학습

In [48]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV

model_xgb = xgb.XGBRegressor(
    objective='reg:squarederror'
)

In [49]:
# params = {
#     'max_depth': [3, 5, 7],
#     'min_child_weight': [1, 3, 5, 7],
#     "reg_alpha": [0.01, 0.1, 1, 10],
#     "subsample": [0.5, 0.75, 1],
#     "colsample_bytree": [0, 0.5, 1]
# }

# grid = GridSearchCV(
#     model_xgb,
#     param_grid = params,
#     cv=5
# )

# grid.fit(
#     X_train,
#     y_train,
#     eval_set=[(X_train, y_train),(X_val, y_val)],
#     eval_metric='rmse'
# )

In [50]:
# grid.best_params_
{'colsample_bytree': 0.5,
 'max_depth': 7,
 'min_child_weight': 7,
 'reg_alpha': 1,
 'subsample': 0.75}

{'colsample_bytree': 0.5,
 'max_depth': 7,
 'min_child_weight': 7,
 'reg_alpha': 1,
 'subsample': 0.75}

In [56]:
model_xgb = xgb.XGBRegressor(
    objective='reg:squarederror',
    max_depth=7,
    min_child_weight=7,
    subsample=0.75,
    reg_alpha=1,
    colsample_bytree=0.5
)

model_xgb.fit(
    X_train,
    y_train,
    eval_set=[(X_train, y_train),(X_val, y_val)],
    eval_metric='rmse'
)

[0]	validation_0-rmse:9.10797	validation_1-rmse:9.35648
[1]	validation_0-rmse:8.24772	validation_1-rmse:8.46662
[2]	validation_0-rmse:7.48533	validation_1-rmse:7.68389
[3]	validation_0-rmse:6.77943	validation_1-rmse:6.96653
[4]	validation_0-rmse:6.14558	validation_1-rmse:6.29678
[5]	validation_0-rmse:5.58178	validation_1-rmse:5.7284
[6]	validation_0-rmse:5.06454	validation_1-rmse:5.19484
[7]	validation_0-rmse:4.60293	validation_1-rmse:4.719
[8]	validation_0-rmse:4.18705	validation_1-rmse:4.29885
[9]	validation_0-rmse:3.81344	validation_1-rmse:3.9234
[10]	validation_0-rmse:3.48343	validation_1-rmse:3.5872
[11]	validation_0-rmse:3.18579	validation_1-rmse:3.28093
[12]	validation_0-rmse:2.92881	validation_1-rmse:3.02659
[13]	validation_0-rmse:2.69929	validation_1-rmse:2.80252
[14]	validation_0-rmse:2.48718	validation_1-rmse:2.58711
[15]	validation_0-rmse:2.29841	validation_1-rmse:2.40936
[16]	validation_0-rmse:2.12514	validation_1-rmse:2.24884
[17]	validation_0-rmse:1.98135	validation_1-rmse:2.10769
[18]	validation_0-rmse:1.83831	validation_1-rmse:1.96664
[19]	validation_0-rmse:1.71746	validation_1-rmse:1.84358
[20]	validation_0-rmse:1.60875	validation_1-rmse:1.73873
[21]	validation_0-rmse:1.51755	validation_1-rmse:1.65227
[22]	validation_0-rmse:1.44392	validation_1-rmse:1.57721
[23]	validation_0-rmse:1.36336	validation_1-rmse:1.50202
[24]	validation_0-rmse:1.30056	validation_1-rmse:1.44508
[25]	validation_0-rmse:1.23957	validation_1-rmse:1.39393
[26]	validation_0-rmse:1.19299	validation_1-rmse:1.34488
[27]	validation_0-rmse:1.14475	validation_1-rmse:1.31286
[28]	validation_0-rmse:1.10371	validation_1-rmse:1.27338
[29]	validation_0-rmse:1.06359	validation_1-rmse:1.25022
[30]	validation_0-rmse:1.03552	validation_1-rmse:1.2236
[31]	validation_0-rmse:1.016	validation_1-rmse:1.20194
[32]	validation_0-rmse:0.985093	validation_1-rmse:1.18411
[33]	validation_0-rmse:0.96438	validation_1-rmse:1.17284
[34]	validation_0-rmse:0.94954	validation_1-rmse:1.1586
[35]	validation_0-rmse:0.930662	validation_1-rmse:1.13894
[36]	validation_0-rmse:0.918419	validation_1-rmse:1.1317
[37]	validation_0-rmse:0.893721	validation_1-rmse:1.12959
[38]	validation_0-rmse:0.882366	validation_1-rmse:1.12147
[39]	validation_0-rmse:0.869969	validation_1-rmse:1.11078
[40]	validation_0-rmse:0.852196	validation_1-rmse:1.10755
[41]	validation_0-rmse:0.839911	validation_1-rmse:1.09525
[42]	validation_0-rmse:0.828118	validation_1-rmse:1.08709
[43]	validation_0-rmse:0.82209	validation_1-rmse:1.08207
[44]	validation_0-rmse:0.811759	validation_1-rmse:1.07154
[45]	validation_0-rmse:0.804717	validation_1-rmse:1.06594
[46]	validation_0-rmse:0.794891	validation_1-rmse:1.05867
[47]	validation_0-rmse:0.787371	validation_1-rmse:1.05726
[48]	validation_0-rmse:0.774293	validation_1-rmse:1.0549
[49]	validation_0-rmse:0.762759	validation_1-rmse:1.05444
[50]	validation_0-rmse:0.752752	validation_1-rmse:1.06082
[51]	validation_0-rmse:0.746596	validation_1-rmse:1.05514
[52]	validation_0-rmse:0.739064	validation_1-rmse:1.05264
[53]	validation_0-rmse:0.730044	validation_1-rmse:1.04006
[54]	validation_0-rmse:0.726477	validation_1-rmse:1.03393
[55]	validation_0-rmse:0.718867	validation_1-rmse:1.03135
[56]	validation_0-rmse:0.715236	validation_1-rmse:1.02693
[57]	validation_0-rmse:0.708793	validation_1-rmse:1.02731
[58]	validation_0-rmse:0.70295	validation_1-rmse:1.02626
[59]	validation_0-rmse:0.69839	validation_1-rmse:1.02137
[60]	validation_0-rmse:0.694152	validation_1-rmse:1.02179
[61]	validation_0-rmse:0.688731	validation_1-rmse:1.01605
[62]	validation_0-rmse:0.684859	validation_1-rmse:1.01762
[63]	validation_0-rmse:0.677845	validation_1-rmse:1.02076
[64]	validation_0-rmse:0.670776	validation_1-rmse:1.01006
[65]	validation_0-rmse:0.665255	validation_1-rmse:1.01001
[66]	validation_0-rmse:0.660626	validation_1-rmse:1.00982
[67]	validation_0-rmse:0.65636	validation_1-rmse:1.00751
[68]	validation_0-rmse:0.649989	validation_1-rmse:1.0037
[69]	validation_0-rmse:0.647011	validation_1-rmse:1.00366
[70]	validation_0-rmse:0.645833	validation_1-rmse:1.00404
[71]	validation_0-rmse:0.642093	validation_1-rmse:1.00054
[72]	validation_0-rmse:0.638905	validation_1-rmse:0.998166
[73]	validation_0-rmse:0.635039	validation_1-rmse:1.00193
[74]	validation_0-rmse:0.627031	validation_1-rmse:0.99647
[75]	validation_0-rmse:0.624405	validation_1-rmse:0.997893
[76]	validation_0-rmse:0.618916	validation_1-rmse:1.00093
[77]	validation_0-rmse:0.612952	validation_1-rmse:0.997063
[78]	validation_0-rmse:0.608963	validation_1-rmse:0.993529
[79]	validation_0-rmse:0.608898	validation_1-rmse:0.993189
[80]	validation_0-rmse:0.605978	validation_1-rmse:0.991473
[81]	validation_0-rmse:0.603891	validation_1-rmse:0.98962
[82]	validation_0-rmse:0.603435	validation_1-rmse:0.990547
[83]	validation_0-rmse:0.60108	validation_1-rmse:0.987614
[84]	validation_0-rmse:0.599097	validation_1-rmse:0.984301
[85]	validation_0-rmse:0.595553	validation_1-rmse:0.980642
[86]	validation_0-rmse:0.59386	validation_1-rmse:0.980744
[87]	validation_0-rmse:0.592264	validation_1-rmse:0.978185
[88]	validation_0-rmse:0.586783	validation_1-rmse:0.97767
[89]	validation_0-rmse:0.583911	validation_1-rmse:0.979608
[90]	validation_0-rmse:0.579347	validation_1-rmse:0.974176
[91]	validation_0-rmse:0.576193	validation_1-rmse:0.970386
[92]	validation_0-rmse:0.574285	validation_1-rmse:0.972741
[93]	validation_0-rmse:0.571862	validation_1-rmse:0.972744
[94]	validation_0-rmse:0.567274	validation_1-rmse:0.9717
[95]	validation_0-rmse:0.564158	validation_1-rmse:0.971232
[96]	validation_0-rmse:0.557922	validation_1-rmse:0.969531
[97]	validation_0-rmse:0.553567	validation_1-rmse:0.969466
[98]	validation_0-rmse:0.551529	validation_1-rmse:0.965463
[99]	validation_0-rmse:0.546482	validation_1-rmse:0.964446

XGBRegressor(colsample_bytree=0.5, max_depth=7, min_child_weight=7,
             objective='reg:squarederror', reg_alpha=1, subsample=0.75)

In [57]:
print("xgb train score : ", model_xgb.score(X_train, y_train))
print("xgb val score : ", model_xgb.score(X_val, y_val))
print("xgb test score : ", model_xgb.score(X_test, y_test))

xgb train score :  0.9740550304223407
xgb val score :  0.8966701066239334
xgb test score :  0.8186507453018702